version: "3"
services:
  mongodb:
    image: 'mongo'
    ports:
      - "27200:27200"
    command: mongod --port 27200 --bind_ip_all
  web:
    depends_on:
      - mongodb
    build: .
    ports:
      - "8082:8082"
    # command: ["./wait-for-it.sh", "mongodb:27200", "-s", "--", "python", "setup.py", "&&", "python", "setup.py"]
    # command: 
    #   - ./wait-for-it.sh
    #   - mongodb:27200
    #   - -s
    #   - --
    #   - python
    #   - setup.py
    #   - 
    #   - python
    #   - setup.py
    # command: ["python", "server.py"]
    command: bash -c "./wait-for-it.sh mongodb:27200 -s -- python setup.py && python server.py"
    container_name: conceptproject